# Generated by Django 2.2.2 on 2019-08-28 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('size', models.IntegerField()),
                ('file_type', models.CharField(default='rosbag', max_length=127)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(null=True)),
                ('analyzed_at', models.DateTimeField(null=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('status', models.CharField(default='registered', max_length=127)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('messages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RosbagTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosbag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='originals.Original')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='originals.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=255)),
                ('file_path', models.CharField(default='', max_length=255)),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='originals.FileType')),
                ('rosbag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='originals.Original')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='', max_length=255)),
                ('frame_count', models.IntegerField()),
                ('analyzed_info', models.CharField(default='', max_length=255)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='originals.Original')),
            ],
        ),
    ]
