# Generated by Django 2.2.2 on 2020-01-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcandidate',
            name='original',
            field=models.IntegerField(),
        ),
    ]
