# Generated by Django 2.2.2 on 2019-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pod_log',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='job',
            name='unknown_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
