# Generated by Django 3.1.9 on 2021-11-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190902_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_config',
            field=models.CharField(max_length=2047),
        ),
    ]
