# Generated by Django 2.2.2 on 2019-08-28 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('description', models.CharField(max_length=127)),
                ('label_type', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_flag', models.BooleanField(default=False)),
                ('owner_id', models.IntegerField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='KlassSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_flag', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='KlassKlassSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.TextField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('klass_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.KlassSet')),
            ],
        ),
    ]
