# Generated by Django 2.2.2 on 2020-01-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klassklassset',
            name='delete_flag',
        ),
    ]
