# Generated by Django 2.2.2 on 2019-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetobject',
            name='instance',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
