# Generated by Django 2.2.2 on 2019-11-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_datasetobject_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('user', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.Annotation')),
            ],
        ),
    ]
