# Generated by Django 2.2.2 on 2019-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_framelock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetobjectannotation',
            name='delete_flag',
        ),
        migrations.AddField(
            model_name='datasetobject',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
