# Generated by Django 2.2.2 on 2020-01-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_framelock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='delete_flag',
        ),
        migrations.RemoveField(
            model_name='archivedlabeldataset',
            name='delete_flag',
        ),
    ]
