# Generated by Django 3.0.2 on 2020-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20200122_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='frame',
            field=models.IntegerField(default=0),
        ),
    ]
