Vagrant.configure("2") do |config|

   config.vm.define 'automan-labeling' do |machine|
    machine.vm.box = "ubuntu/xenial64"
    config.disksize.size = "30GB"
    machine.vm.hostname = 'automan-labeling'
    machine.vm.network :private_network,ip: "192.168.33.33"
    machine.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      vbox.cpus = 2
      vbox.memory = 4096
    end

     machine.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "automan-labeling.yaml"
      ansible.version = "latest"
      ansible.verbose = false
      ansible.install = true
      ansible.limit = "automan-labeling"
      ansible.inventory_path = "hosts"
    end
  end
end
